### ISSUE TITLE
Do proper password hashing for email/password accounts

### ISSUE THREAD

**Issue by tla** [tla/stemmaweb#123]
The passwords for email/password login need to be checked server-side (well, middleware-side) against the hashed form stored on Stemmarest.

**Comment by tla** [comment]
Here is a link to the code in the master branch that shows how the passphrases are encrypted... 
https://github.com/tla/stemmaweb/blob/e01c1839f5ddf0e4728b810bfe03d6b43e8a1922/lib/Catalyst/Authentication/Store/Neo4p/User.pm#L50

**Comment by peter-gy** [comment]
Thank you for linking the related code!
