### ISSUE TITLE
Stemweb algorithms unavailable

### ISSUE THREAD

**Issue by GermaineG** [tla/stemmaweb#68]
Apologies if this happens to be the wrong place for this question, but I haven't found a support mail address for stemmaweb.

Right now if one tries to run a Stemweb algorithm in Stemmaweb, there is only the option to use 'Pars', the rest of the algorithms is missing from the dropdown menu. Roughly 2 weeks ago for a short while you could also select RHM, NJ and Semstem. It never provided a result or any feedback though and the next day the options were missing again and have been missing since.

To me it looks like the Stemweb server is not available (since Pars is not part of Stemweb). Would it be possible to provide some information about the current status? Is it only a temporary problem or will this part of Stemmaweb/Stemweb most likely stay that way in the future?

**Comment by tla** [comment]
Thanks for reporting this - I'll check with the maintainers of the Stemweb server and see what's going on.

**Comment by tla** [comment]
An update - the Stemweb maintainer has spotted the problem, but won't be able to fix it until he's back from holiday next week.

**Comment by GermaineG** [comment]
Thank you very much for the update, that sounds very good. I'll retry then at some point after next week.

**Comment by GermaineG** [comment]
May I ask if there are any news on this issue? For me the problem persists, I can only select 'Pars' as Stemweb algorithm.

**Comment by tla** [comment]
The Stemweb service will not be back up anytime soon - yesterday, however, I was sent the source code for the RHM algorithm. I'm going to try to integrate this directly into Stemmaweb in the next couple of weeks, and see if I can enable NeighborNet as well. Semstem may or may not come back, since its authors think that RHM is more reliable.

**Comment by tla** [comment]
The Stemweb service is back up, though there may yet be problems with RHM...
