### ISSUE TITLE
It would be good to be able to click on the arrow "majority" and see what mss are included.

### ISSUE THREAD

**Issue by anahitsafaryan** [tla/stemmaweb#73]

**Comment by seretan** [comment]
Would that be an option?

<img width="1365" alt="capture d ecran 2019-02-28 a 14 52 15" src="https://user-images.githubusercontent.com/1819697/53571257-bb81e300-3b68-11e9-8e9f-20a3c4e5e7b8.png">

**Comment by anahitsafaryan** [comment]
It looks nice to me.

**Comment by tla** [comment]
Duplicate of #23
