### ISSUE TITLE
a platform to see the lemmatised text so that we can check

### ISSUE THREAD

**Issue by anahitsafaryan** [tla/stemmaweb#76]

**Comment by seretan** [comment]
#79 
<img width="142" alt="capture d ecran 2019-01-14 a 13 50 32" src="https://user-images.githubusercontent.com/1819697/53499628-02100880-3aa9-11e9-864a-5cf789209e4d.png">

**Comment by seretan** [comment]
(On a second thought, I am not sure you meant lemmatized in the linguistic sense or the critical apparatus one.)

**Comment by tla** [comment]
@seretan nice :) though what @anahitsafaryan meant in this issue (as far as I understand it) is a way to read the lemma text (i.e. the nodes colored red) as text, rather than as nodes in a graph. Like a pop-up overlay of the running text for the section in question.

**Comment by tla** [comment]
@anahitsafaryan There is now a "View running text" button on the relationship mapper, with which you can get the lemma text as well as the text of any particular witness (though not, so far, the a.c. witnesses.) Let me know what you think, and don't forget to hold down Shift when you reload to make sure all the Javascript gets refreshed...
