### ISSUE TITLE
Docker build not working: maketestdb.pl missing in master

### ISSUE THREAD

**Issue by raffiii** [tla/stemmaweb#87]
Because I could log in to stemmaweb neither with Google ("Please come back later") nor with a stemmaweb registration (It asks me to fill a recaptcha but none is shown) I tried to build it locally. It fails on step 10/11 when running `maketestdb.pl` which I found on the production branch but not in the master and the dockerfile doesn't switch branches.

**Comment by tla** [comment]
Yes, that documentation and that Dockerfile is out of date; Stemmaweb now relies on the Stemmarest backend (DHUniWien/tradition_repo), which is another service of its own. I am intrigued that the Google login didn't work, though - can you try it again and tell me if it still fails?

**Comment by raffiii** [comment]
Thanks for that response, I tried it again (already multiple times previously) and the login POST request has a '500 Internal Server Error' after about 50 seconds (I guess some kind of timeout). Hope some of these screenshots may help:
![Screenshot from 2020-07-06 16-40-37](https://user-images.githubusercontent.com/45318499/86606075-d3147b80-bfa7-11ea-8df7-f634dfeca9b7.png)
![Screenshot from 2020-07-06 16-51-20](https://user-images.githubusercontent.com/45318499/86606976-01468b00-bfa9-11ea-8cfd-5f144eb78dbb.png)

**Comment by tla** [comment]
OK, I've looked into this and it looks like a long-standing data corruption bug has come home to roost, which can't be easily fixed. (Additionally, the recaptcha API has changed.) If you write to me on my Uni Wien address and tell me what you are trying to use Stemmaweb for, I might be able to help you further.
