### ISSUE TITLE
Registration with Stemmaweb requires a recaptcha but doesn't open a recaptcha dialogue

### ISSUE THREAD

**Issue by AlinaOs** [tla/stemmaweb#90]
I tried to register for stemmaweb via the stemmaweb registration (no google- or other openID). I went this path: stemmaweb.stemmaweb/ -> Sign in/Register -> Sign in with Stemmaweb -> register.
After filling in the registration form and clicking the button "Register", the **warning "User appears not to have submitted a recaptcha"** appears, **even though no recaptcha dialogue has opened** on the button click and the form doesn't contain any checkbox for a recaptcha.
The problem appears **both in Firefox and Google Chrome** and on different computers, so I guess its a problem with the code, not the browser settigs (I also normally see recaptcha dialogues on websites and haven't turned them off via browser settings or something).
I tried to sign in with my newly set mail address and password, to see if the registration has nonetheless worked (maybe it has been stored internally despite of the missing-captcha-warning) , but I couldn't sign in, so the missing recaptcha dialogue actually **prevents users without Google Mail or OpenID from registering to and using stemmaweb**.

**Comment by tla** [comment]
Thanks for letting me know that this isn't working! I'll try to look into it in the next couple of days.

**Comment by AlinaOs** [comment]
Thank you very much!
In the meantime I tried to sign in via Google. This first seems to work, since stemmaweb is receiving some data, but then it only gives the info "Please come back later" in several different languages. I tried it later and in different browsers (Chrome and Firefox), where the same thing happened.
So if you find the time to investigate the problem with the stemmaweb signin, maybe you'd also like to have a look at the Google signin.

**Comment by tla** [comment]
Hi, can you tell me what does (or doesn't) work on https://v2.stemmaweb.net/
? (This will be the replacement for the current elderly Stemmaweb service,
but isn't yet feature complete...)

**Comment by AlinaOs** [comment]
Hey!
Google signin gives the same message as described above.
The stemmaweb signin has a recaptcha checkbox now but when clicking on "Register" ist gives the error message: "Can't connect to www.google.com:443 (Try again) Try again at /usr/local/share/perl5/site_perl/LWP/Protocol/http.pm line 50."

**Comment by tla** [comment]
Hi - I just tried a test registration on v2.stemmaweb.net and it worked
fine; can you please try again? Maybe there was a transient network issue.

As for Google signin, what happens if you try a second time (also on v2)? I
am aware of a bug where the initial registration gives an error, but the
account has in fact been created, so first want to make sure this
isn't that.

>

**Comment by AlinaOs** [comment]
Hey, thanks for your answer!
Now the registration with stemmaweb worked on v2! The last time, when it didn't work, it did not open the recaptcha dialogue with the pictures, I could just check the checkbox. Now it worked fine and I'm registered.
The google signin seems to have worked too on v2. I clicked on Signin with Google and suddenly I was signed in (without having to enter my password or mail adress).


Von Outlook<http://aka.ms/weboutlook> gesendet.

________________________________
Von: tla <notifications@github.com>
Gesendet: Freitag, 22. Januar 2021 13:33
An: tla/stemmaweb <stemmaweb@noreply.github.com>
Cc: AlinaOs <alina.o@live.de>; Author <author@noreply.github.com>
Betreff: Re: [tla/stemmaweb] Registration with Stemmaweb requires a recaptcha but doesn't open a recaptcha dialogue (#90)


Hi - I just tried a test registration on v2.stemmaweb.net and it worked
fine; can you please try again? Maybe there was a transient network issue.

As for Google signin, what happens if you try a second time (also on v2)? I
am aware of a bug where the initial registration gives an error, but the
account has in fact been created, so first want to make sure this
isn't that.

**Comment by tla** [comment]
Okay great! It may even be that the Google login will work the second time on stemmaweb.net, in case you want to check out more features there. But that system has an old and buggy database, so I won't be surprised if more problems crop up...
