### ISSUE TITLE
Click node to root stemma

### ISSUE THREAD

**Issue by jorisvanzundert** [tla/stemmaweb#92]
There seems to be no out-of-the-box way to root a stemma/tree in GraphViz/graphviz.js. The only way I see right now is rewriting the dot if a user clicks a node so that this node is placed first in the dot file. Another way might be using neato and pre-define/calculate all node positions (but then why using a lay out algorithm at all?)

**Comment by tla** [comment]
Memory jogged; this is something that has always been done via an API call, in this case:

    POST $STEMMAREST_ENDPOINT/tradition/$TRAD_ID/stemma/$STEMMA_NAME/reorient/$SIGIL

and that gets you back the new stemma definition, including dot for rendering.

**Comment by jorisvanzundert** [comment]
Ah, okay... however.. what about moving this to the client? Do we in/on principle want the client to do more, or rather not? It's kind of an architectural directive I guess.

**Comment by tla** [comment]
Well, the call does need to be made to the server, so that the root is stored. I think it's fine as it is, that the server sends a dot definition (it's as good a specification as anything, and pretty simple, since it just lists nodes, edges, and whether extant or hypothetical) and it's up to the client to work out how to render that.

**Comment by jorisvanzundert** [comment]
Hmm... not sure what's going wrong, but I can't get StemmaRest to return a reoriented stemma.

http://localhost:3000/api/tradition/b9a69c03-8a19-40e8-95fc-e9c7d206c488/stemma/stemma%20of%20Tomas/

works fine, but neither

* http://localhost:3000/api/tradition/b9a69c03-8a19-40e8-95fc-e9c7d206c488/stemma/stemma%20of%20Tomas/reorient/%CE%B4/  (using `δ` as `node_id`)
* http://localhost:3000/api/tradition/b9a69c03-8a19-40e8-95fc-e9c7d206c488/stemma/stemma%20of%20Tomas/reorient/svg-0.stemma%20of%20Tomas.%CE%B4/ (using `svg-0.stemma of Tomas.δ` as `node_id`) 

work. I get a 500: url contains unescaped characters; but it does not, I use encodeURI().

Neither works:

http://localhost:3000/api/tradition/b9a69c03-8a19-40e8-95fc-e9c7d206c488/stemma/stemma%20of%20Tomas/reorient/node14 or /D

I get a 405 Method not allowed. At least that's slightly better, but still not the desired result.

So what *is* the API expecting?

**Comment by tla** [comment]
I think I answered this offline, but just for the record: if you are seeing a 405 response, it means you are probably calling GET instead of POST or POST instead of PUT or some such, with your request.
