### ISSUE TITLE
UI element to modify tradition metadata

### ISSUE THREAD

**Issue by tla** [tla/stemmaweb#97]

**Comment by jorisvanzundert** [comment]
See https://dhuniwien.github.io/tradition_repo/#-890226420-1479144569 for the metadata (put). Should be editable like so:

* direction: a drop down with fixed values LTR/RTL
* is_public: toggle yes/no
* name: free text
* language: 
* owner: visible only as admin, dropdown of users(?)

* id: not editable

**Comment by tla** [comment]
Thanks! A couple of remarks:
- direction has three possible values: LR RL BI (bidirectional makes the graph run top to bottom)
- language is also free text
